function [x2y] = rationalfit(x,y)
% CREATEFIT(x,y)
%  Create a fit.
%
%  Data for 'x2y' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  Auto-generated by MATLAB on 31-Oct-2015 18:13:42
%
%% Fit: 'x2y'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'rat22' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'Bisquare';
opts.StartPoint = [0.765516788149002 0.795199901137063 0.186872604554379 ...
    0.489764395788231 0.445586200710899];

% Fit model to data.
[x2y, gof] = fit( xData, yData, ft, opts );

